name: Revive
main: me.xiaox.revive.Revive
author: [D_xiaox]
depend: [Vault, ProtocolLib]
api-version: 1.13
<<<<<<< HEAD
version: 1.2.2
=======
version: 1.1.0
>>>>>>> a3f10b7550205e7499679600d4cef63b6543821d
commands:
  re:
